### ISSUE TITLE
proposal: use https://github.com/fatih/gomodifytags

### ISSUE THREAD

**Issue by kpurdon** [syohex/emacs-go-add-tags#6]
See: https://github.com/fatih/gomodifytags

It could be better long term to move this package to use the new go tool by fatih. I suspect it will have more active maintenance and new features. Also using it would always allow this package to be on par with the vim equivalent.

Thoughts?

**Comment by syohex** [comment]
Thanks for information. It looks good. Using it is better than using my own implementation. I'll try to switch to use it instead of own implementation. (But I'm busy now, please wait to implement it).

**Comment by kpurdon** [comment]
Ya no worries. Just thought I'd share. Thanks for your work.

**Comment by brantou** [comment]
@kpurdon I implemented  [go-tag](https://github.com/brantou/emacs-go-tag) based on [gomodifytags](https://github.com/fatih/gomodifytags),  welcome to try! @syohex So sorry, I can not wait.

**Comment by kpurdon** [comment]
good w/ current implementation, or could switch to go-tag ... closing
