### ISSUE TITLE
Customize list of tags

### ISSUE THREAD

**Issue by ikawalec** [syohex/emacs-go-add-tags#9]
Would it be possible to customize: https://github.com/emacsorphanage/go-add-tags/blob/master/go-add-tags.el#L144?

For instance, I'd like to add mapstructure annotation.

@syohex

**Comment by syohex** [comment]
I have no longer push permission. Please mention current maintainer.

**Comment by ikawalec** [comment]
@tarsius could you take a look?

**Comment by tarsius** [comment]
@ikawalec Could you open a pull-request? I don't use go and have no idea what fields make sense. Also not sure what a "field" is. (Also is "ex" a field? If not, then the "ex" in the library commentary should be changed to "e.g.".)

**Comment by ikawalec** [comment]
Sure: https://github.com/emacsorphanage/go-add-tags/pull/10

Ideally, the list of default tags: (json yaml toml mapstructure) should be configurable, so that I can override it similar to style:

```
(custom-set-variables
 '(go-add-tags-style 'lower-camel-case))
```

**Comment by tarsius** [comment]
Is (json yaml toml mapstructure) the complete set of fields or are there others that are just not commonly used? I am asking because maybe we should restrict completion to the provided choices, or maybe not.

**Comment by tarsius** [comment]
I mean, your previous answer implies, there are more, but could you please be explicit about it. And if there are more, then why not add them all instead of making the user customize an option? Or is the set infinite, i.e. users can define their own fields?

**Comment by ikawalec** [comment]
It's dynamic. There might be some other libraries that are using different tags, or you could even create a new tag if you need. The current list is the most common I can think of.

**Comment by tarsius** [comment]
I modified you commit a bit and added two more. Please give it a try.
